---------------------
--COMPANY_CATEGORY (회사 업종)
---------------------
DROP TABLE COMPANY_CATEGORY CASCADE CONSTRAINTS;
CREATE TABLE COMPANY_CATEGORY (
    CATEGORY_CODE       NUMBER          PRIMARY KEY           --업종 코드
    , CATEGORY_NAME       VARCHAR2(20)    NOT NULL              --업종 이름
)
;

--COMPANY_CATEGORY 시퀀스
DROP SEQUENCE SEQ_COM_CATEGORY_NO;
CREATE SEQUENCE SEQ_COM_CATEGORY_NO NOCACHE NOCYCLE;


COMMIT;    

---------------------
--COM (회사)
---------------------
DROP TABLE COM CASCADE CONSTRAINTS;
CREATE TABLE COM (
    COM_CODE                  NUMBER            PRIMARY KEY     --회사 번호
    , COM_CATEGORY_CODE       NUMBER            NOT NULL        --카테고리
    , COM_NAME                VARCHAR2(50)      NOT NULL        --사명
    , COM_TEL                 CHAR(10)          NOT NULL        --회사 대표 연락처
    , COM_FOUNDATION_DATE     TIMESTAMP          NOT NULL        --창립일
    , COM_REGISTRATION_NO     CHAR(12)                          --사업자등록번호
    , CONSTRAINT FK_COM_CATEGORY FOREIGN KEY(COM_CATEGORY_CODE) REFERENCES COMPANY_CATEGORY(CATEGORY_CODE)
);

--COM 시퀀스
DROP SEQUENCE SEQ_COM_NO;
CREATE SEQUENCE SEQ_COM_NO NOCACHE NOCYCLE;

COMMIT;
----------------------
--DEPT (부서)
----------------------
DROP TABLE DEPT CASCADE CONSTRAINTS;
CREATE TABLE DEPT (
    DEPT_CODE                 NUMBER             PRIMARY KEY       --부서번호
    , HIGH_DEPT_CODE          NUMBER                               --상위부서     
    , DEPT_NAME               VARCHAR2(50)       NOT NULL          --부서이름
    , DEPT_HEAD_CODE          NUMBER                               --부서장
    , DEPT_STATUS             CHAR(1)            DEFAULT 'N' CHECK(DEPT_STATUS IN ('N','D'))  
    , DEPT_DEPTH              NUMBER
)
;
--DEPT 시퀀스
DROP SEQUENCE SEQ_DEPT_NO;
CREATE SEQUENCE SEQ_DEPT_NO NOCACHE NOCYCLE;

COMMIT;
----------------------
--RANK (직위)
----------------------
DROP TABLE RANK CASCADE CONSTRAINTS;
CREATE TABLE RANK (
    RANK_CODE           NUMBER              PRIMARY KEY     --직위번호
    , RANK_NAME         VARCHAR2(30)        NOT NULL        --직위이름
    , RANK_LEVEL        NUMBER              NOT NULL        --직위위계 (1에 가까울수록 높음)
    , RANK_STATUS       CHAR(1)             DEFAULT 'N' CHECK(RANK_STATUS IN ('N','D'))
)
;
--RANK 시퀀스
DROP SEQUENCE SEQ_RANK_NO;
CREATE SEQUENCE SEQ_RANK_NO NOCACHE NOCYCLE;

COMMIT;
----------------------
--JOB (직무)
----------------------
DROP TABLE JOB CASCADE CONSTRAINTS;
CREATE TABLE JOB (
    JOB_CODE            NUMBER          PRIMARY KEY         --직무번호
    , JOB_NAME          VARCHAR2(30)     NOT NULL           --직무이름
    , JOB_STATUS        CHAR(1)          DEFAULT 'N' CHECK(JOB_STATUS IN ('N','D'))
)
;
--JOB 시퀀스
DROP SEQUENCE SEQ_JOB_NO;
CREATE SEQUENCE SEQ_JOB_NO NOCACHE NOCYCLE;

COMMIT;
----------------------
--RIGHT (권한)
----------------------
DROP TABLE RIGHT CASCADE CONSTRAINTS;
CREATE TABLE RIGHT (
    RIGHT_CODE         NUMBER            PRIMARY KEY        --권한번호
    , RIGHT_NAME       VARCHAR2(15)      NOT NULL           --권한이름
)
;
--RIGHT 시퀀스
DROP SEQUENCE SEQ_RIGHT_NO;
CREATE SEQUENCE SEQ_RIGHT_NO NOCACHE NOCYCLE;

COMMIT;
----------------------
--EMP
----------------------
DROP TABLE EMP CASCADE CONSTRAINTS;

CREATE TABLE EMP (
    EMP_CODE                NUMBER              PRIMARY KEY     --사원번호
    , COM_CODE              NUMBER              NOT NULL        --회사번호
    , DEPT_CODE             NUMBER              NOT NULL        --부서번호
    , RANK_CODE             NUMBER              NOT NULL        --직위번호
    , EMP_JOB_CODE          NUMBER              NOT NULL        --직무번호
    , RIGHT_CODE            NUMBER              NOT NULL        --계정권한
    , EMP_NAME              VARCHAR2(20)                        --이름
    , EMP_ID                VARCHAR2(30)        UNIQUE          --아이디
    , EMP_PWD               VARCHAR2(100)                       --비밀번호
    , EMP_E_MAIL            VARCHAR2(50)        UNIQUE          --이메일
    , EMP_BIRTHDAY          CHAR(10)                            --생년월일
    , EMP_TEL               CHAR(11)            UNIQUE          --사내번호
    , EMP_PHONE             CHAR(11)            UNIQUE          --개인 휴대전화
    , EMP_JOIN_DATE         TIMESTAMP           DEFAULT SYSDATE --입사일
    , EMP_PROMOTION_DATE    TIMESTAMP                           --진급일
    , EMP_ADDRESS1          VARCHAR2(100)                       --주소1
    , EMP_ADDRESS2          VARCHAR2(100)                       --주소2
    , EMP_STATUS            CHAR(1)            DEFAULT 'N' CHECK(EMP_STATUS IN ('N','R','Q')) --상태, N:일반, R:휴직, Q:퇴사                   --상태
    , EMP_ACCOUNT_NO        VARCHAR2(30)        UNIQUE          --계좌번호
    , EMP_PROFILE_NAME      VARCHAR2(100)                       --프로필 사진이름
    , EMP_LAST_LOGIN_DATE   TIMESTAMP                           --마지막 접속일
    , EMP_FILE_NAME         VARCHAR2(100)       UNIQUE          --서명파일 이름
    , CONSTRAINT FK_EMP_COM FOREIGN KEY(COM_CODE) REFERENCES COM(COM_CODE)
    , CONSTRAINT FK_EMP_DEPT FOREIGN KEY(DEPT_CODE) REFERENCES DEPT(DEPT_CODE)
    , CONSTRAINT FK_EMP_RANK FOREIGN KEY(RANK_CODE) REFERENCES RANK(RANK_CODE)
    , CONSTRAINT FK_EMP_JOB FOREIGN KEY(EMP_JOB_CODE) REFERENCES JOB(JOB_CODE)
    , CONSTRAINT FK_EMP_RIGHT FOREIGN KEY(RIGHT_CODE) REFERENCES RIGHT(RIGHT_CODE)
);

--EMP 시퀀스
DROP SEQUENCE SEQ_EMP_NO;
CREATE SEQUENCE SEQ_EMP_NO NOCACHE NOCYCLE;

COMMIT;
---------------------
--CEO (대표이사)
---------------------
DROP TABLE CEO CASCADE CONSTRAINTS;
CREATE TABLE CEO (
    CEO_CODE                  NUMBER            PRIMARY KEY     --대표이사 번호
    , COM_CODE                NUMBER            NOT NULL        --회사 번호
    , EMP_CODE                NUMBER            NOT NULL        --참조할 사원 테이블 
    , CEO_TEL                 CHAR(11)          NOT NULL        --대표이사 번호
    , CEO_REGISTER_DATE       TIMESTAMP                         --등록일
    , CEO_QUIT_DATE           TIMESTAMP                         --삭제일
    , CONSTRAINT FK_CEO_COM FOREIGN KEY(COM_CODE) REFERENCES COM(COM_CODE) --COM 참조
    , CONSTRAINT FK_CEO_EMP FOREIGN KEY(COM_CODE) REFERENCES EMP(EMP_CODE)--EMP 참조
)
;

--CEO 시퀀스
DROP SEQUENCE SEQ_CEO_NO;
CREATE SEQUENCE SEQ_CEO_NO NOCACHE NOCYCLE;

COMMIT;

--------------------
-- COMMUTE (근태)
--------------------
DROP TABLE COMMUTE CASCADE CONSTRAINTS;
CREATE TABLE COMMUTE (
      COM_CODE              NUMBER           PRIMARY KEY
    , ECODE                 NUMBER           NOT NULL
    , START_TIME            VARCHAR2(30)     NULL
    , START_TIME_FORMAT     VARCHAR2(30)     NULL
    , END_TIME              VARCHAR2(30)     NULL
    , END_TIME_FORMAT       VARCHAR2(30)     NULL
    , WORKING_TIME          VARCHAR2(30)     NULL
    , ENROLL_DATE           TIMESTAMP        DEFAULT SYSDATE
    , COM_STATUS            VARCHAR2(30)     NOT NULL               --정상출근, 지각, 조기퇴근, 결근
    , CONSTRAINT FK_COM_EMP_CODE FOREIGN KEY(ECODE) REFERENCES EMP(EMP_CODE)
);

DROP SEQUENCE SEQ_COM_CODE_NO;
CREATE SEQUENCE SEQ_COM_CODE_NO NOCACHE NOCYCLE;


--------------------
-- OVERWORK (시간 외 근무)
--------------------
DROP TABLE OVERWORK CASCADE CONSTRAINTS;
CREATE TABLE OVERWORK(
        OVER_CODE            NUMBER           PRIMARY KEY
      , ECODE                NUMBER           NOT NULL
      , DEPT_CODE            NUMBER           NOT NULL
      , OVER_DATE            VARCHAR2(30)     NOT NULL
      , OVER_TIME            NUMBER           NOT NULL
      , OVER_NAME            VARCHAR2(500)     NOT NULL
      , OVER_REASON          VARCHAR2(1000)     NOT NULL
      , OVER_ENROLLDATE      TIMESTAMP        DEFAULT SYSDATE
      , OVER_APPROVAL        CHAR(1)          DEFAULT 'W' CHECK(OVER_APPROVAL IN ('W','A','C'))
      , CONSTRAINT FK_OVER_EMP_CODE FOREIGN KEY(ECODE) REFERENCES EMP(EMP_CODE)
      , CONSTRAINT FK_OVER_DEPT_CODE FOREIGN KEY(DEPT_CODE) REFERENCES DEPT(DEPT_CODE)
);

DROP SEQUENCE SEQ_OVER_CODE_NO;
CREATE SEQUENCE SEQ_OVER_CODE_NO NOCACHE NOCYCLE;


--------------------
-- DAYOFF (휴가)
--------------------
DROP TABLE DAYOFF CASCADE CONSTRAINTS;
CREATE TABLE DAYOFF(
         OFF_CODE               NUMBER           PRIMARY KEY
       , ECODE                  NUMBER           NOT NULL
       , DEPT_CODE              NUMBER           NOT NULL
       , OFF_START_DATE         VARCHAR2(30)     NOT NULL
       , OFF_END_DATE           VARCHAR2(30)     NOT NULL
       , OFF_DAYS               NUMBER           NOT NULL
       , OFF_REASON             VARCHAR2(1000)   NOT NULL
       , OFF_ENROLLDATE         TIMESTAMP        DEFAULT SYSDATE         
       , OFF_APPROVAL           CHAR(1)          DEFAULT 'W' CHECK(OFF_APPROVAL IN ('W','A','C'))
       , CONSTRAINT FK_DAYOFF_EMP_CODE FOREIGN KEY(ECODE) REFERENCES EMP(EMP_CODE)
       , CONSTRAINT FK_DAYOFF_DEPT_CODE FOREIGN KEY(DEPT_CODE) REFERENCES DEPT(DEPT_CODE)
);

DROP SEQUENCE SEQ_DAYOFF_CODE_NO;
CREATE SEQUENCE SEQ_DAYOFF_CODE_NO NOCACHE NOCYCLE;

--------------------
-- DAYOFF_COUNT(휴가개수) -> RANK에 따른
--------------------
DROP TABLE DAYOFF_COUNT CASCADE CONSTRAINTS;
CREATE TABLE DAYOFF_COUNT(
         COUNT_CODE               NUMBER           PRIMARY KEY
       , RANK_CODE                NUMBER           NOT NULL
       , OFF_ALL                  NUMBER           NOT NULL
       , CONSTRAINT FK_COUNT_RANK_CODE FOREIGN KEY(RANK_CODE) REFERENCES RANK(RANK_CODE)
);

DROP SEQUENCE SEQ_DAYOFF_COUNT_CODE_NO;
CREATE SEQUENCE SEQ_DAYOFF_COUNT_CODE_NO NOCACHE NOCYCLE;

-- 결재문서-----------------------------------------------------------------------
DROP TABLE APPROVAL_DOC CASCADE CONSTRAINTS;
CREATE TABLE APPROVAL_DOC(
DOC_CODE NUMBER PRIMARY KEY
, PERIOD_CODE NUMBER NOT NULL
, DOC_FORM_CODE NUMBER NOT NULL
, EMP_CODE NUMBER NOT NULL
, DOC_TITLE VARCHAR2(300) NOT NULL
, DOC_ENROLL_DATE TIMESTAMP DEFAULT SYSDATE
, DOC_UPDATED TIMESTAMP
, DOC_STATUS CHAR(1) DEFAULT 'N' CHECK(DOC_STATUS IN ('D','N','T'))
, DOC_APPR_DATE TIMESTAMP
);
DROP SEQUENCE SEQ_APPROVAL_DOC_CODE;
CREATE SEQUENCE SEQ_APPROVAL_DOC_CODE NOCACHE NOCYCLE;
--전자결재 첨부파일----------------------------------------------------------------
DROP TABLE APPROVAL_FILE CASCADE CONSTRAINTS;
CREATE TABLE APPROVAL_FILE(
FILE_CODE NUMBER PRIMARY KEY
, DOC_CODE NUMBER NOT NULL
, ORIGIN_NAME VARCHAR2(200) NOT NULL
, UPLOAD_NAME VARCHAR2(200) NOT NULL
);
DROP SEQUENCE SEQ_APPROVAL_FILE_CODE;
CREATE SEQUENCE SEQ_APPROVAL_FILE_CODE NOCACHE NOCYCLE;
--결재문서 보존연한----------------------------------------------------------------
DROP TABLE DOC_RETENTION_PERIOD CASCADE CONSTRAINTS;
CREATE TABLE DOC_RETENTION_PERIOD(
PERIOD_CODE NUMBER PRIMARY KEY
, PERIOD VARCHAR2(50) NOT NULL
);
DROP SEQUENCE SEQ_DOC_RETENTION_PERIOD_CODE;
CREATE SEQUENCE SEQ_DOC_RETENTION_PERIOD_CODE NOCACHE NOCYCLE;
--문서 즐겨찾기-------------------------------------------------------------------
DROP TABLE IMPORTANT_DOC CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_DOC_RETENTION_PERIOD_CODE;
CREATE SEQUENCE SEQ_DOC_RETENTION_PERIOD_CODE NOCACHE NOCYCLE;
--결재참조인----------------------------------------------------------------------
DROP TABLE APPROVAL_REF CASCADE CONSTRAINTS;
CREATE TABLE APPROVAL_REF(
DOC_CODE NUMBER NOT NULL
, REF_EMP_CODE NUMBER NOT NULL
, CHECK_YN CHAR(1) DEFAULT 'N' CHECK(CHECK_YN IN ('Y','N'))
);
--결재자리스트------------------------------------------------------------------------
DROP TABLE APPROVAL_LIST CASCADE CONSTRAINTS;
CREATE TABLE APPROVAL_LIST(
DOC_CODE NUMBER NOT NULL
, APPR_TYPE_CODE NUMBER NOT NULL
, APPR_EMP_CODE NUMBER NOT NULL
, APPR_SEQ NUMBER NOT NULL
, APPR_DATE DATE
, APPR_STATUS CHAR(1) DEFAULT 'W' CHECK(APPR_STATUS IN ('A','C','W'))
);
DROP SEQUENCE SEQ_APPROVAL_LIST_CODE;
CREATE SEQUENCE SEQ_APPROVAL_LIST_CODE NOCACHE NOCYCLE;
--결재타입------------------------------------------------------------------------
DROP TABLE APPROVAL_TYPE CASCADE CONSTRAINTS;
CREATE TABLE APPROVAL_TYPE(
APPR_TYPE_CODE NUMBER PRIMARY KEY
, APPR_TYPE_NAME VARCHAR2(100) NOT NULL
);
DROP SEQUENCE SEQ_APPROVAL_TYPE_CODE;
CREATE SEQUENCE SEQ_APPROVAL_TYPE_CODE NOCACHE NOCYCLE;
--문서양식------------------------------------------------------------------------
DROP TABLE DOC_FORM CASCADE CONSTRAINTS;
CREATE TABLE DOC_FORM(
FORM_CODE NUMBER PRIMARY KEY
, FORM_NAME VARCHAR2(100) NOT NULL
, FORM_INTRO VARCHAR2(1000)
, FORM_USE_YN CHAR(1) DEFAULT 'Y' CHECK(FORM_USE_YN IN ('Y','N'))
);
DROP SEQUENCE SEQ_DOC_FORM_CODE;
CREATE SEQUENCE SEQ_DOC_FORM_CODE NOCACHE NOCYCLE;
--문서양식 매핑------------------------------------------------------------------------
DROP TABLE DOC_FORM_MAPPING CASCADE CONSTRAINTS;
CREATE TABLE DOC_FORM_MAPPING(
FORM_CODE NUMBER NOT NULL
, FORM_DETAIL_CODE NUMBER NOT NULL
, FORM_DETAIL_SEQ NUMBER NOT NULL
);
--문서양식상세 템플릿------------------------------------------------------------------------
DROP TABLE DOC_FORM_DETAIL_TEMPLATE CASCADE CONSTRAINTS;
CREATE TABLE DOC_FORM_DETAIL_TEMPLATE(
FORM_DETAIL_CODE NUMBER PRIMARY KEY
, FORM_DETAIL_NAME VARCHAR2(200) NOT NULL
, FORM_DETAIL_TYPE VARCHAR2(200) NOT NULL
);
DROP SEQUENCE SEQ_DOC_FORM_DETAIL_TEMPLATE_CODE;
CREATE SEQUENCE SEQ_DOC_FORM_DETAIL_TEMPLATE_CODE NOCACHE NOCYCLE;
--문서 작성 데이터------------------------------------------------------------------------
DROP TABLE DOC_DATA CASCADE CONSTRAINTS;
CREATE TABLE DOC_DATA(
DOC_CODE NUMBER NOT NULL
, FORM_DETAIL_CODE NUMBER NOT NULL
, DOC_CONTENT VARCHAR2(4000)
);
--의견남기기------------------------------------------------------------------------
DROP TABLE DOC_COMMENT CASCADE CONSTRAINTS;
CREATE TABLE DOC_COMMENT(
COMMENT_CODE NUMBER PRIMARY KEY
, DOC_CODE NUMBER NOT NULL
, WRITER_CODE NUMBER NOT NULL
, COM_ENROLL_DATE TIMESTAMP DEFAULT SYSDATE
, COM_UPDATED TIMESTAMP
, COM_CONTENT VARCHAR2(4000) NOT NULL
, COM_STATUS CHAR(1) DEFAULT 'N' CHECK(COM_STATUS IN ('D','N','C')));
DROP SEQUENCE SEQ_DOC_COMMENT_CODE;
CREATE SEQUENCE SEQ_DOC_COMMENT_CODE NOCACHE NOCYCLE;

--일정
DROP TABLE CALENDAR CASCADE CONSTRAINTS;
CREATE TABLE CALENDAR (
	CAL_CODE	NUMBER		NOT NULL PRIMARY KEY,
	EMP_CODE	NUMBER	    NOT NULL,
	CAL_TITLE	VARCHAR2(1000)		NULL,
    CAL_TYPE VARCHAR2(100) NULL CHECK(CAL_TYPE IN ('WORK', 'HOME')),
	CAL_START	TIMESTAMP		NULL,
	CAL_END	TIMESTAMP		NULL,
	CAL_ALLDAY	CHAR(5)	DEFAULT 'FALSE'	NULL CHECK (CAL_ALLDAY IN ('TRUE', 'FALSE')),
	CAL_HOLIDAY	CHAR(1)	DEFAULT 'N'	NULL,
	CAL_ENROLLDATE	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	CAL_DEL	CHAR(1)	DEFAULT 'N'	NOT NULL,
    CONSTRAINT FK_CAL_EMP FOREIGN KEY(EMP_CODE) REFERENCES EMP(EMP_CODE)
);

DROP SEQUENCE SEQ_CAL_CODE;
CREATE SEQUENCE SEQ_CAL_CODE NOCACHE NOCYCLE;

--파일 매니저
DROP TABLE FILECLOUD CASCADE CONSTRAINTS;
CREATE TABLE FILECLOUD (
	FILE_CODE	NUMBER		NOT NULL PRIMARY KEY,
	EMP_CODE	NUMBER	    NOT NULL,
	FILE_TITLE	VARCHAR2(1000)		NULL,
    FILE_CONTENT VARCHAR2(2000) NULL,
	FILE_NAME	VARCHAR2(2000)		NULL,
	FILE_ORIGINNAME	VARCHAR2(2000)		NULL,
	FILE_URL	VARCHAR2(2000)		NULL,
	FILE_ENROLLDATE	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	FILE_CNT	NUMBER	DEFAULT 0	NOT NULL,
	FILE_BOOKMARK	CHAR(1)	DEFAULT '0'	NULL,
	FILE_DELDATE	TIMESTAMP		NULL,
	FILE_RANGE	NUMBER		NULL,
    FILE_TYPE   VARCHAR2(30)    NULL,
    FILE_SIZE VARCHAR2(2000)    NULL,
    CONSTRAINT FK_FILE_EMP FOREIGN KEY(EMP_CODE) REFERENCES EMP(EMP_CODE)
);

DROP SEQUENCE SEQ_FILE_CODE;
CREATE SEQUENCE SEQ_FILE_CODE NOCACHE NOCYCLE;


----
-- 사내공지
----


DROP TABLE NOTICE CASCADE CONSTRAINTS;
CREATE TABLE NOTICE(
      NOTICE_CODE         NUMBER           PRIMARY KEY
    , NOTICE_TITLE        VARCHAR2(100)    NOT NULL
    , NOTICE_CONTENT      VARCHAR2(2000)   NOT NULL
    , NOTICE_VIEWS        NUMBER           DEFAULT 0
    , NOTICE_DATE         TIMESTAMP        DEFAULT SYSDATE
    , NOTICE_UPDATE       TIMESTAMP        DEFAULT SYSDATE
    , NOTICE_DELETE       TIMESTAMP        
);

DROP SEQUENCE SEQ_NOTICE_CODE;
CREATE SEQUENCE SEQ_NOTICE_CODE NOCACHE NOCYCLE;

DROP TABLE NOTICE_FILE CASCADE CONSTRAINTS;
CREATE TABLE NOTICE_FILE (
   NOTICE_FILE_CODE      NUMBER       PRIMARY KEY
    , NOTICE_CODE        NUMBER      
    , NOTICE_ORIGIN_NAME VARCHAR2(1000)
    , NOTICE_CHANGE_NAME VARCHAR2(1000)
    , NOTICE_FILE_ROOT   VARCHAR2(1000)
    );  
  

ALTER TABLE NOTICE_FILE ADD CONSTRAINT FK_NOTICE_CODE
FOREIGN KEY(NOTICE_CODE) REFERENCES NOTICE(NOTICE_CODE);

DROP SEQUENCE SEQ_NOTICE_FILE_CODE;
CREATE SEQUENCE SEQ_NOTICE_FILE_CODE NOCACHE NOCYCLE;

---
--메일
----

DROP TABLE MAIL CASCADE CONSTRAINTS;
CREATE TABLE MAIL (
      MAIL_CODE          NUMBER           PRIMARY KEY
    , EMP_CODE           NUMBER            
    , MAIL_SENDER        VARCHAR2(100)    NOT NULL
    , MAIL_TITLE         VARCHAR2(100)    NOT NULL
    , MAIL_CONTENT       VARCHAR2(2000)   NOT NULL
    , MAIL_SENDDATE      TIMESTAMP        DEFAULT SYSDATE
    , MAIL_RECEIVER      VARCHAR2(100)    NOT NULL
    , MAIL_VIEWS         NUMBER           DEFAULT 0
    , MAIL_DELETE        TIMESTAMP          
    ) ;

ALTER TABLE MAIL ADD CONSTRAINT FK_EMP_CODE
FOREIGN KEY(EMP_CODE) REFERENCES EMP(EMP_CODE);  

DROP SEQUENCE SEQ_MAIL_CODE;
CREATE SEQUENCE SEQ_MAIL_CODE NOCACHE NOCYCLE;

DROP TABLE MAIL_FILE CASCADE CONSTRAINTS;
CREATE TABLE MAIL_FILE (
    MAIL_FILE_CODE     NUMBER       PRIMARY KEY
    , MAIL_CODE        NUMBER      
    , MAIL_ORIGIN_NAME VARCHAR2(1000)
    , MAIL_CHANGE_NAME VARCHAR2(1000)
    , MAIL_FILE_ROOT   VARCHAR2(1000)
    );  
    
ALTER TABLE MAIL_FILE ADD CONSTRAINT FK_MAIL_CODE
FOREIGN KEY(MAIL_CODE) REFERENCES MAIL(MAIL_CODE);


DROP SEQUENCE SEQ_MAIL_FILE_CODE;
CREATE SEQUENCE SEQ_MAIL_FILE_CODE NOCACHE NOCYCLE;

----------------------------------------------------------------------------
--- 주소록 ---------------------------------------------------------------
----------------------------------------------------------------------------
DROP TABLE CONTACTS CASCADE CONSTRAINTS;
CREATE TABLE CONTACTS(
      CON_NO             NUMBER               PRIMARY KEY
    , CON_WRITER         NUMBER               NOT NULL
    , CON_NAME           VARCHAR2(10)         NOT NULL
    , CON_EMAIL          VARCHAR2(30)         NULL
    , CON_TEL            CHAR(13)             NULL
    , CON_COMPANY        VARCHAR2(30)         NULL
    , CON_MEMO           VARCHAR2(100)        NULL
    , FILE_NAME          VARCHAR2(100)        NULL
    , CONSTRAINT FK_CON_EMP FOREIGN KEY(CON_WRITER) REFERENCES EMP(EMP_CODE)
);

DROP SEQUENCE SEQ_CONTACTS_NO;
CREATE SEQUENCE SEQ_CONTACTS_NO NOCACHE NOCYCLE;

----------------------------------------------------------------------------
--- 예약 ---------------------------------------------------------------
----------------------------------------------------------------------------
DROP TABLE BOOKING CASCADE CONSTRAINTS;
CREATE TABLE BOOKING (
	 BK_NO                   NUMBER                 PRIMARY KEY
   , BK_TARGET_NO          NUMBER                 NOT NULL
   , BK_WRITER             NUMBER                 NOT NULL
   , BK_TYPE               CHAR(1)                NULL CHECK(BK_TYPE IN ('A', 'M'))
   , BK_START	             TIMESTAMP		          NOT NULL
   , START_TIME            TIMESTAMP		          NOT NULL
   , BK_END	               TIMESTAMP		          NOT NULL
   , END_TIME              TIMESTAMP		          NOT NULL
   , CONSTRAINT FK_BK_EMP FOREIGN KEY(BK_WRITER) REFERENCES EMP(EMP_CODE)
);

DROP SEQUENCE SEQ_BOOKING_NO;
CREATE SEQUENCE SEQ_BOOKING_NO NOCACHE NOCYCLE;

----------------------------------------------------------------------------
--- 예약_타겟 ----------------------------------------------------------
----------------------------------------------------------------------------
DROP TABLE TARGET CASCADE CONSTRAINTS;
CREATE TABLE TARGET(
      TARGET_NO                NUMBER                PRIMARY KEY
    , TARGET_NAME              VARCHAR2(30)          NOT NULL
    , TARGET_TAG               VARCHAR2(20)          NULL CHECK(TARGET_TAG IN ('비품','회의실'))
    , TARGET_IMAGE             VARCHAR2(50)          NULL
);

DROP SEQUENCE SEQ_TARGET_NO;
CREATE SEQUENCE SEQ_TARGET_NO NOCACHE NOCYCLE;